name: Pender Prod Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Build Rust Program
      run: cargo build --release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pender-rust-binary
        path: target/release/pender-rust

  Deploy:
    needs: Build
    runs-on: ubuntu-20.04
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: pender-rust-binary
        
    - name: Copy Executable to VPS
      uses: appleboy/scp-action@master
      with:
        source: pender-rust
        target: "/root/pender-prod"
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        
    - name: SSH into VPS and Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /root/pender-prod
          git pull
          sudo systemctl restart pender-prod
