name: Pender Staging Build

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust Program
        run: cargo build --release

      - name: Copy Executable to VPS
        uses: appleboy/scp-action@master
        with:
          source: "target/release/pender-rust"
          target: "/root/pender-staging"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}

      - name: SSH into VPS and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/pender-staging
            git pull
            sudo systemctl restart pender-staging
