name: Pender Build

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust Program
        run: cargo build --release

      - name: Copy Executable to VPS
        uses: appleboy/scp-action@master
        with:
          local_file: /target/release/pender-rust
          remote_path: /root/Pender/target/release/
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}

      - name: SSH into VPS and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo systemctl restart pender
